# Generated by Django 3.2.2 on 2021-05-16 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_of_audiobook', models.TextField(max_length=100)),
                ('author_of_title', models.TextField(max_length=100)),
                ('narrator_of_audiobook', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_podcast', models.TextField(max_length=100)),
                ('host_of_podcast', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_song', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
