# Generated by Django 3.2.2 on 2021-05-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server', '0002_auto_20210517_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audiobook',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
