# Generated by Django 3.2.2 on 2021-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server', '0003_auto_20210517_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
