# Generated by Django 3.2.2 on 2021-05-17 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server', '0004_alter_song_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_of_audiobook', models.TextField(max_length=100)),
                ('author_of_title', models.TextField(max_length=100)),
                ('narrator_of_audiobook', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
