# Generated by Django 3.2.2 on 2021-05-17 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server', '0005_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_podcast', models.TextField(max_length=100)),
                ('host_of_podcast', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
