# Generated by Django 3.2.2 on 2021-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_server', '0007_auto_20210517_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
